# Generated by Django 3.2.11 on 2022-04-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('people_limit', models.IntegerField()),
                ('place', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
