# Generated by Django 3.2.11 on 2022-04-18 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='join_users',
            field=models.ManyToManyField(related_name='join_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
